# k8s/front-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80          # Port externe du service
      targetPort: 5173  # Port du container Vite
      nodePort: 30002   # Port NodePort
  type: NodePort
