apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 80           # Port du service interne (utilisé par l’Ingress)
    targetPort: 80     # Port exposé dans le conteneur (serveur Vite/Nginx)
  type: ClusterIP      # Service interne, exposé via l'Ingress
