apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend       # Nom du déploiement frontend
  labels:
    app: frontend
spec:
  replicas: 1          # Nombre de pods frontend
  selector:
    matchLabels:
      app: frontend    # Label utilisé pour associer le pod au déploiement
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: soxnahawaa/jenkins_front:latest   # Image Docker du frontend (React)
        ports:
        - containerPort: 80    # Port exposé par le conteneur (Nginx)
        env:
        - name: VITE_API_URL  
          value: "http://backend-service:5000/api"  # ✅ Utilise le nom du service Kubernetes
